// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCquDU7etZ4kLa2UhPxQXT9dEVW66ypdgw',
    appId: '1:217635364127:web:2cbea88f9b6376b1e5a42a',
    messagingSenderId: '217635364127',
    projectId: 'kasir-bengkel',
    authDomain: 'kasir-bengkel.firebaseapp.com',
    storageBucket: 'kasir-bengkel.firebasestorage.app',
    measurementId: 'G-JZVRPQWPRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJNomFlaExeCSVR-S6YHB-CFP2j8CT0g',
    appId: '1:217635364127:android:b0159515fe9ad802e5a42a',
    messagingSenderId: '217635364127',
    projectId: 'kasir-bengkel',
    storageBucket: 'kasir-bengkel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgrXZRVbzNE7u0mRvLV4y289CgFinhS58',
    appId: '1:217635364127:ios:b2376d30db970c31e5a42a',
    messagingSenderId: '217635364127',
    projectId: 'kasir-bengkel',
    storageBucket: 'kasir-bengkel.firebasestorage.app',
    iosBundleId: 'com.example.kasirBengkel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgrXZRVbzNE7u0mRvLV4y289CgFinhS58',
    appId: '1:217635364127:ios:b2376d30db970c31e5a42a',
    messagingSenderId: '217635364127',
    projectId: 'kasir-bengkel',
    storageBucket: 'kasir-bengkel.firebasestorage.app',
    iosBundleId: 'com.example.kasirBengkel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquDU7etZ4kLa2UhPxQXT9dEVW66ypdgw',
    appId: '1:217635364127:web:a0ebe56786523fe9e5a42a',
    messagingSenderId: '217635364127',
    projectId: 'kasir-bengkel',
    authDomain: 'kasir-bengkel.firebaseapp.com',
    storageBucket: 'kasir-bengkel.firebasestorage.app',
    measurementId: 'G-STNF7CKT2Q',
  );
}
